env: "development"

database:
  host: localhost
  port: "7111"
  user: "postgres"
  password: "postgres"
  dbname: "fitnow"
  max_attempts: 5
  ssl: disable

minio_s3:
  url: localhost:9000
  access_key: minioadmin
  secret_key: minioadmin
  ssl: false

clients:
  auth_client:
    address: "localhost:44044"
    timeout: 5s
    retries: 5
    insecure: true

http_server:
  host: 0.0.0.0
  port: 7000
  timeout: 120s
  debug: true
  idle_timeout: 60s




