basePath: /api/v1
definitions:
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  auth.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  domain.ErrorResponse:
    properties:
      description:
        type: string
      key:
        type: string
    type: object
  domain.User:
    properties:
      access_token:
        type: string
      email:
        type: string
      id:
        type: string
      refresh_token:
        type: string
      title:
        type: string
    type: object
  traincategory.CreateTrainCategoryRequest:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  traincategory.CreateTrainCategoryResponse:
    properties:
      category:
        $ref: '#/definitions/traincategory.TrainCategoryDB'
    type: object
  traincategory.TrainCategoryDB:
    properties:
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
      version:
        type: integer
    type: object
  traincategory.UpdateTrainCategoryRequest:
    properties:
      title:
        type: string
    required:
    - title
    type: object
host: localhost:7111
info:
  contact:
    url: https://github.com/Sanchir01
  description: This is a gateway server
  termsOfService: http://swagger.io/terms/
  title: "\U0001F680 FITNOW"
  version: 0.0.1
paths:
  /auth/login:
    post:
      description: Login user by email
      parameters:
      - description: Login body json
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User by email
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Login
      tags:
      - auth
  /auth/register:
    post:
      description: Register user by email
      parameters:
      - description: Register user and return
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Registered user
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Register
      tags:
      - auth
  /train/category:
    get:
      description: Get all train category
      produces:
      - application/json
      responses:
        "200":
          description: All data category trains
          schema:
            items:
              $ref: '#/definitions/traincategory.TrainCategoryDB'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: GetAllTrainCategory
      tags:
      - train-category
    post:
      description: Create category train
      parameters:
      - description: Create body json
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/traincategory.CreateTrainCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: create category response
          schema:
            $ref: '#/definitions/traincategory.CreateTrainCategoryResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: CreateTrainCategory
      tags:
      - train-category
  /train/category/{id}:
    delete:
      description: delete category train by id
      produces:
      - application/json
      responses:
        "200":
          description: create category response
          schema:
            $ref: '#/definitions/traincategory.CreateTrainCategoryResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: DeleteTrainCategory
      tags:
      - train-category
    put:
      description: Update category train by id
      parameters:
      - description: Update body json
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/traincategory.UpdateTrainCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: create category response
          schema:
            $ref: '#/definitions/traincategory.CreateTrainCategoryResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: UpdateTrainCategory
      tags:
      - train-category
securityDefinitions:
  BearerAuth:
    description: 'Enter your JWT token (you can use it with or without "Bearer " prefix).
      Example: "eyJhbGc..." or "Bearer eyJhbGc..."'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
